#!/usr/bin/python3

import re
import sys

from typing import Pattern

splicer:Pattern = re.compile('^@@(.*)@@$', re.M)

indata:str = sys.stdin.read()
for data in splicer.findall(indata):
    with open(data, 'r') as fromfile:
        indata = indata.replace(f'\n@@{data}@@\n', f'\n{fromfile.read().strip()}\n')

sys.stdout.write(indata)
