#!/bin/bash

# testing the test vector generator with notmuch
set -e

workdir=$(mktemp -d)
mkdir -p -m 0700 "$workdir/"{g,m/{new,cur,tmp}}
cleanup() {
    rm -rf "$workdir"
}
trap cleanup EXIT

export GNUPGHOME="$workdir/g"
export NOTMUCH_CONFIG="$workdir/nm-config"
cat >"$NOTMUCH_CONFIG" <<EOF
[new]
[database]
path=$workdir/m
[user]
name=Bob Babbage
primary_email=bob@openpgp.example
[new]
tags=unread;inbox;
ignore=
[maildir]
synchronize_flags=true
[search]
exclude_tags=deleted;spam;
EOF
# from https://tools.ietf.org/html/draft-bre-openpgp-samples-00#section-2.1:
gpg --batch --quiet --no-tty --import < alice@openpgp.example.pub.asc

# from https://tools.ietf.org/html/draft-bre-openpgp-samples-00#section-3.2:
gpg --batch --quiet --no-tty --import < bob@openpgp.example.sec.asc

# from https://www.ietf.org/id/draft-dkg-lamps-samples-01.html#name-certificate-authority-certi
gpgsm --batch --no-tty --quiet --import < sample-ca.pem
# trust the CA:
cat > "$GNUPGHOME/trustlist.txt" <<EOF
4D:E0:FF:63:C0:E9:EC:01:29:11:C8:7A:EE:DA:3A:9A:7F:6E:C1:0D S
EOF
gpgsm --list-keys
gpg --quiet --batch --no-tty --pinentry-mode=loopback --passphrase '' --quick-gen-key 'Local Test Suite Trust Anchor' futuredefault
gpg --quiet --batch --no-tty --yes --lsign alice@openpgp.example
notmuch new --quiet
notmuch config set index.decrypt true
for x in *.eml; do
    echo "inserting $x"
    < "$x" notmuch insert
done
notmuch count
for x in $(./generate-test-vectors list-vectors); do
    echo "extracting crypto for $x"
    notmuch show --format=json --entire-thread=false --verify=true "id:$x@protected-headers.example" \
        | python3 -c 'import json,sys; json.dump(json.load(sys.stdin)[0][0][0]["crypto"], sys.stdout, indent=1)'
    echo
done
notmuch dump
