#!/bin/bash

set -e
publishhost="${publishhost:-che.mayfirst.org}"
if [ "$1" = release ]; then
    printf 'publishing to official server...\n' >&2
    suffix=
else
    printf 'publishing to staging server...\n' >&2
    suffix=-staging
fi
assembly=$(mktemp -d)
cleanup() {
    rm -rf "$assembly"
}
trap cleanup EXIT

printf "publishing to %s…" "$publishhost" >&2
mkdir -p "$assembly"/{messages/{new,tmp,cur},meta}
cp *.eml "$assembly/messages/cur/"
cp distribution/{protected-headers-imap${suffix}.service,dovecot.acls} "$assembly/meta/"
cp distribution/config${suffix}/dovecot.conf "$assembly/meta/"
tar --create -C "$assembly" messages meta | ssh "$publishhost" tar -x -C "/srv/protected-headers${suffix}"
printf "done\n" >&2
